/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface CedGapi {
    'clientConfig': any;
    'gapi': any;
    'getClient': () => Promise<any>;
    'getUserData': () => Promise<any>;
    'initialise': (config: {}) => Promise<unknown>;
    'isAuthenticated': () => Promise<any>;
    'login': () => Promise<any>;
    'logout': () => Promise<any>;
    'refreshToken': () => Promise<any>;
  }
}

declare global {


  interface HTMLCedGapiElement extends Components.CedGapi, HTMLStencilElement {}
  var HTMLCedGapiElement: {
    prototype: HTMLCedGapiElement;
    new (): HTMLCedGapiElement;
  };
  interface HTMLElementTagNameMap {
    'ced-gapi': HTMLCedGapiElement;
  }
}

declare namespace LocalJSX {
  interface CedGapi extends JSXBase.HTMLAttributes<HTMLCedGapiElement> {
    'clientConfig'?: any;
    'gapi'?: any;
  }

  interface IntrinsicElements {
    'ced-gapi': CedGapi;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


